spring:
  thymeleaf:
    mode: HTML5
    encoding: utf-8
    servlet:
      content-type: text/html
    cache: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8
    username: root
    password: admin123
  jpa:
    hibernate:
      # 和数据库表结构同步更新
      ddl-auto: update
    show-sql: true
logging:
  level:
    root: info
    com.liaolong: debug
  file:
    path: /log
    name: blog-dev.log
server:
  port: 8081

